version: '3'

services:
  catalog:
    image: mariadb:11.8
    environment:
      - MARIADB_ROOT_PASSWORD=testpassword
      - MARIADB_USER=irods
      - MARIADB_PASSWORD=testpassword
    # For parity with mysql 8.0, we use utf8mb4 charset and utf8mb4_uca1400_as_cs collation (for case sensitivity), and disable the binary log
    command: "--transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_uca1400_as_cs --disable-log-bin"

  irods-catalog-provider:
    build:
      context: ..
      dockerfile: ${dockerfile}
    depends_on:
      - catalog
    volumes:
      - shared_volume:/irods_testing_environment_mount_dir
    # The core test suite for iRODS uses SIGHUP to reload the server's configuration often.
    # To keep the iRODS Rule Language from failing and producing RE_UNABLE_TO_READ_SESSION_VAR,
    # we bump the maximum amount of shared memory from 64mb to 100mb. This is required because
    # iRODS 5 can have two Agent Factories running simultaneously (due to the SIGHUP).
    shm_size: 100mb

  irods-catalog-consumer:
    build:
      context: ..
      dockerfile: ${dockerfile}
    depends_on:
      - irods-catalog-provider
    volumes:
      - shared_volume:/irods_testing_environment_mount_dir
    # The core test suite for iRODS uses SIGHUP to reload the server's configuration often.
    # To keep the iRODS Rule Language from failing and producing RE_UNABLE_TO_READ_SESSION_VAR,
    # we bump the maximum amount of shared memory from 64mb to 100mb. This is required because
    # iRODS 5 can have two Agent Factories running simultaneously (due to the SIGHUP).
    shm_size: 100mb

# This volume is mounted on all test servers for detached mode testing which
# requires a common vault.
volumes:
    shared_volume:
